import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/contexts/authContext";
import { CartProvider } from "@/contexts/CartContext";
import { Providers } from "./Providers";
import Chat from "@/components/ComunityChat/Chat";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});
const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Dev </> Navigator ",
  description: "Generated by create Grupo #3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <AuthProvider>
        <CartProvider>
          <html lang="es">
            <body className={`${montserrat.variable} ${lato.variable}`}>
              <header>
                <Navbar />
              </header>
              <main>{children}</main>
              <Chat />
              <Footer />
            </body>
          </html>
        </CartProvider>
      </AuthProvider>
    </Providers>
  );
}
